packages:
  - 'ui/**/*'
  - 'bin'

catalog:
  shogiground: ^0.10.1
  shogiops: ^0.18.0
  snabbdom: ^3.6.2
  '@badrap/result': ^0.2.13
  'chart.js': ^4.4.7
  '@types/node': ^20.17.12
  tsx: ^4.19.2
  '@textcomplete/core': '^0.1.13'
  '@textcomplete/textarea': '^0.1.13'
  '@yaireo/tagify': '^4.33.1'
  '@types/yaireo__tagify': '^4.27.0'
  'debounce-promise': '^3.1.2'
  '@types/debounce-promise': '^3.1.9'
