name: Build server

on:
  push:
    paths:
      - '.github/workflows/server.yml'
      - 'app/**'
      - 'conf/**'
      - 'modules/**'
      - 'project/**'
      - 'translation/**'
      - 'build.sbt'
      - 'lila.sh'
      - '.sbtopts.default'
    branches-ignore:
      - 'l10n_master2'
  pull_request:
    paths:
      - '.github/workflows/server.yml'
      - 'app/**'
      - 'conf/**'
      - 'modules/**'
      - 'project/**'
      - 'translation/source/**'
      - 'build.sbt'
      - 'lila.sh'
      - '.sbtopts.default'

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - run: ./lila.sh -Depoll=true "test;stage"
